version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/dbexpense
      SPRING_DATASOURCE_USERNAME: gastos
      SPRING_DATASOURCE_PASSWORD: 123
      APP_NAME: expenses-manager
      API-OWNER:
      API-PROVIDER:
      API-SANCTION:
      API-FILEMANAGER: http://localhost:8081/fileManager

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: dbexpense
      MYSQL_USER: gastos
      MYSQL_PASSWORD: 123
      MYSQL_ROOT_PASSWORD: root_password
      TZ: America/Argentina/Buenos_Aires #Zona horaria
    volumes:
      - ./dbscript/db.sql:/docker-entrypoint-initdb.d/01-db.sql
      - ./dbscript/trigers.sql:/docker-entrypoint-initdb.d/02-trigers.sql
      - ./dbscript/init.sql:/docker-entrypoint-initdb.d/03-init.sql
      - ./dbscript/noIdividual.sql:/docker-entrypoint-initdb.d/04-noIdividual.sql
      - ./dbscript/individual.sql:/docker-entrypoint-initdb.d/05-individual.sql

    ports:
      - "3307:3306"
    expose:
      - "3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
